### ISSUE TITLE
[BUG]: "There shoudn't be more than one assignement per line" error

### ISSUE THREAD

**Issue by leodubosclard** [Just1truc/Abricot-Norminette#32] opened 2022-03-17 19:47 UTC
### What happened?

Hi there,

I write this number since, while my use of "Apricot", I found an error of the norminette.

Indeed, this report me an L1 (There shoudn't be more than one assignment per line) while the corresponding code is not what the norminette thinks.

Please resolve this issue as soon as possible.

Cordially. 

Proofs:

![image](https://user-images.githubusercontent.com/47077683/158883575-7c4265e5-9458-434f-be4b-38b690ca1fdb.png)
![image](https://user-images.githubusercontent.com/47077683/158883617-0234a60d-1020-42d1-ab46-048e8caa8851.png)

Edit: 

Par là aussi ça pète (pour aucune raison c'est juste des protos)
![image](https://user-images.githubusercontent.com/47077683/158889377-c51bfd77-0ba9-4357-b3b7-5a9237ffc2a7.png)
![image](https://user-images.githubusercontent.com/47077683/158889393-c440974f-439f-4d49-979d-07ffecbd2a60.png)

### Version

Yes

### What OS are you seeing the problem on?

Fedora based

### Relevant output

```shell
There shoudn't be more than one assignment per line
```

**Comment by Just1truc** [comment] 2022-03-17 21:27
hi,

Thanks for your report. This issue will be fixed soon. This is maybe caused by the recent update that include L1 detection

Yours sincerely

**Comment by Just1truc** [comment] 2022-03-17 22:09
hi,

This issue should have been fixed

thanks

**Closed as completed by Just1truc** 2022-03-17 22:09 UTC
Labels: bug, verified
